#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSociety
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HumaneSociety")]
	public partial class HumaneSocietyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnimal(Animal instance);
    partial void UpdateAnimal(Animal instance);
    partial void DeleteAnimal(Animal instance);
    partial void InsertAdopter(Adopter instance);
    partial void UpdateAdopter(Adopter instance);
    partial void DeleteAdopter(Adopter instance);
    #endregion
		
		public HumaneSocietyDataContext() : 
				base(global::HumaneSociety.Properties.Settings.Default.HumaneSocietyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HumaneSocietyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumaneSocietyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumaneSocietyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumaneSocietyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Animal> Animals
		{
			get
			{
				return this.GetTable<Animal>();
			}
		}
		
		public System.Data.Linq.Table<Adopter> Adopters
		{
			get
			{
				return this.GetTable<Adopter>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Animal")]
	public partial class Animal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _animal_id;
		
		private string _tag_id;
		
		private string _species;
		
		private string _name;
		
		private string _breed;
		
		private string _gender;
		
		private System.Nullable<bool> _neutered_spayed;
		
		private string _age_at_enter_date;
		
		private string _description_notes;
		
		private System.Nullable<bool> _kid_friendly;
		
		private string _maintenance_level;
		
		private System.Nullable<System.DateTime> _enter_date;
		
		private string _source_aquired;
		
		private System.Nullable<int> _room_assignment;
		
		private System.Nullable<int> _daily_food_ration;
		
		private System.Nullable<bool> _shots;
		
		private System.Nullable<System.DateTime> _shots_date;
		
		private System.Nullable<bool> _adopted;
		
		private System.Nullable<System.DateTime> _adopted_date;
		
		private string _adopted_by;
		
		private System.Nullable<double> _price;
		
		private EntitySet<Adopter> _Adopters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onanimal_idChanging(int value);
    partial void Onanimal_idChanged();
    partial void Ontag_idChanging(string value);
    partial void Ontag_idChanged();
    partial void OnspeciesChanging(string value);
    partial void OnspeciesChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnbreedChanging(string value);
    partial void OnbreedChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void Onneutered_spayedChanging(System.Nullable<bool> value);
    partial void Onneutered_spayedChanged();
    partial void Onage_at_enter_dateChanging(string value);
    partial void Onage_at_enter_dateChanged();
    partial void Ondescription_notesChanging(string value);
    partial void Ondescription_notesChanged();
    partial void Onkid_friendlyChanging(System.Nullable<bool> value);
    partial void Onkid_friendlyChanged();
    partial void Onmaintenance_levelChanging(string value);
    partial void Onmaintenance_levelChanged();
    partial void Onenter_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onenter_dateChanged();
    partial void Onsource_aquiredChanging(string value);
    partial void Onsource_aquiredChanged();
    partial void Onroom_assignmentChanging(System.Nullable<int> value);
    partial void Onroom_assignmentChanged();
    partial void Ondaily_food_rationChanging(System.Nullable<int> value);
    partial void Ondaily_food_rationChanged();
    partial void OnshotsChanging(System.Nullable<bool> value);
    partial void OnshotsChanged();
    partial void Onshots_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onshots_dateChanged();
    partial void OnadoptedChanging(System.Nullable<bool> value);
    partial void OnadoptedChanged();
    partial void Onadopted_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onadopted_dateChanged();
    partial void Onadopted_byChanging(string value);
    partial void Onadopted_byChanged();
    partial void OnpriceChanging(System.Nullable<double> value);
    partial void OnpriceChanged();
    #endregion
		
		public Animal()
		{
			this._Adopters = new EntitySet<Adopter>(new Action<Adopter>(this.attach_Adopters), new Action<Adopter>(this.detach_Adopters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_animal_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int animal_id
		{
			get
			{
				return this._animal_id;
			}
			set
			{
				if ((this._animal_id != value))
				{
					this.Onanimal_idChanging(value);
					this.SendPropertyChanging();
					this._animal_id = value;
					this.SendPropertyChanged("animal_id");
					this.Onanimal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag_id", DbType="VarChar(50)")]
		public string tag_id
		{
			get
			{
				return this._tag_id;
			}
			set
			{
				if ((this._tag_id != value))
				{
					this.Ontag_idChanging(value);
					this.SendPropertyChanging();
					this._tag_id = value;
					this.SendPropertyChanged("tag_id");
					this.Ontag_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_species", DbType="VarChar(50)")]
		public string species
		{
			get
			{
				return this._species;
			}
			set
			{
				if ((this._species != value))
				{
					this.OnspeciesChanging(value);
					this.SendPropertyChanging();
					this._species = value;
					this.SendPropertyChanged("species");
					this.OnspeciesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_breed", DbType="VarChar(50)")]
		public string breed
		{
			get
			{
				return this._breed;
			}
			set
			{
				if ((this._breed != value))
				{
					this.OnbreedChanging(value);
					this.SendPropertyChanging();
					this._breed = value;
					this.SendPropertyChanged("breed");
					this.OnbreedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(6)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_neutered_spayed", DbType="Bit")]
		public System.Nullable<bool> neutered_spayed
		{
			get
			{
				return this._neutered_spayed;
			}
			set
			{
				if ((this._neutered_spayed != value))
				{
					this.Onneutered_spayedChanging(value);
					this.SendPropertyChanging();
					this._neutered_spayed = value;
					this.SendPropertyChanged("neutered_spayed");
					this.Onneutered_spayedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age_at_enter_date", DbType="VarChar(25)")]
		public string age_at_enter_date
		{
			get
			{
				return this._age_at_enter_date;
			}
			set
			{
				if ((this._age_at_enter_date != value))
				{
					this.Onage_at_enter_dateChanging(value);
					this.SendPropertyChanging();
					this._age_at_enter_date = value;
					this.SendPropertyChanged("age_at_enter_date");
					this.Onage_at_enter_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description_notes", DbType="VarChar(150)")]
		public string description_notes
		{
			get
			{
				return this._description_notes;
			}
			set
			{
				if ((this._description_notes != value))
				{
					this.Ondescription_notesChanging(value);
					this.SendPropertyChanging();
					this._description_notes = value;
					this.SendPropertyChanged("description_notes");
					this.Ondescription_notesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kid_friendly", DbType="Bit")]
		public System.Nullable<bool> kid_friendly
		{
			get
			{
				return this._kid_friendly;
			}
			set
			{
				if ((this._kid_friendly != value))
				{
					this.Onkid_friendlyChanging(value);
					this.SendPropertyChanging();
					this._kid_friendly = value;
					this.SendPropertyChanged("kid_friendly");
					this.Onkid_friendlyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maintenance_level", DbType="VarChar(6)")]
		public string maintenance_level
		{
			get
			{
				return this._maintenance_level;
			}
			set
			{
				if ((this._maintenance_level != value))
				{
					this.Onmaintenance_levelChanging(value);
					this.SendPropertyChanging();
					this._maintenance_level = value;
					this.SendPropertyChanged("maintenance_level");
					this.Onmaintenance_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enter_date", DbType="DateTime2")]
		public System.Nullable<System.DateTime> enter_date
		{
			get
			{
				return this._enter_date;
			}
			set
			{
				if ((this._enter_date != value))
				{
					this.Onenter_dateChanging(value);
					this.SendPropertyChanging();
					this._enter_date = value;
					this.SendPropertyChanged("enter_date");
					this.Onenter_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_aquired", DbType="VarChar(50)")]
		public string source_aquired
		{
			get
			{
				return this._source_aquired;
			}
			set
			{
				if ((this._source_aquired != value))
				{
					this.Onsource_aquiredChanging(value);
					this.SendPropertyChanging();
					this._source_aquired = value;
					this.SendPropertyChanged("source_aquired");
					this.Onsource_aquiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_assignment", DbType="Int")]
		public System.Nullable<int> room_assignment
		{
			get
			{
				return this._room_assignment;
			}
			set
			{
				if ((this._room_assignment != value))
				{
					this.Onroom_assignmentChanging(value);
					this.SendPropertyChanging();
					this._room_assignment = value;
					this.SendPropertyChanged("room_assignment");
					this.Onroom_assignmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daily_food_ration", DbType="Int")]
		public System.Nullable<int> daily_food_ration
		{
			get
			{
				return this._daily_food_ration;
			}
			set
			{
				if ((this._daily_food_ration != value))
				{
					this.Ondaily_food_rationChanging(value);
					this.SendPropertyChanging();
					this._daily_food_ration = value;
					this.SendPropertyChanged("daily_food_ration");
					this.Ondaily_food_rationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shots", DbType="Bit")]
		public System.Nullable<bool> shots
		{
			get
			{
				return this._shots;
			}
			set
			{
				if ((this._shots != value))
				{
					this.OnshotsChanging(value);
					this.SendPropertyChanging();
					this._shots = value;
					this.SendPropertyChanged("shots");
					this.OnshotsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shots_date", DbType="DateTime2")]
		public System.Nullable<System.DateTime> shots_date
		{
			get
			{
				return this._shots_date;
			}
			set
			{
				if ((this._shots_date != value))
				{
					this.Onshots_dateChanging(value);
					this.SendPropertyChanging();
					this._shots_date = value;
					this.SendPropertyChanged("shots_date");
					this.Onshots_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adopted", DbType="Bit")]
		public System.Nullable<bool> adopted
		{
			get
			{
				return this._adopted;
			}
			set
			{
				if ((this._adopted != value))
				{
					this.OnadoptedChanging(value);
					this.SendPropertyChanging();
					this._adopted = value;
					this.SendPropertyChanged("adopted");
					this.OnadoptedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adopted_date", DbType="DateTime2")]
		public System.Nullable<System.DateTime> adopted_date
		{
			get
			{
				return this._adopted_date;
			}
			set
			{
				if ((this._adopted_date != value))
				{
					this.Onadopted_dateChanging(value);
					this.SendPropertyChanging();
					this._adopted_date = value;
					this.SendPropertyChanged("adopted_date");
					this.Onadopted_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adopted_by", DbType="VarChar(50)")]
		public string adopted_by
		{
			get
			{
				return this._adopted_by;
			}
			set
			{
				if ((this._adopted_by != value))
				{
					this.Onadopted_byChanging(value);
					this.SendPropertyChanging();
					this._adopted_by = value;
					this.SendPropertyChanged("adopted_by");
					this.Onadopted_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Animal_Adopter", Storage="_Adopters", ThisKey="animal_id", OtherKey="animal_id")]
		public EntitySet<Adopter> Adopters
		{
			get
			{
				return this._Adopters;
			}
			set
			{
				this._Adopters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Adopters(Adopter entity)
		{
			this.SendPropertyChanging();
			entity.Animal = this;
		}
		
		private void detach_Adopters(Adopter entity)
		{
			this.SendPropertyChanging();
			entity.Animal = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adopter")]
	public partial class Adopter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _member_id;
		
		private string _name;
		
		private string _phone_number;
		
		private string _email;
		
		private string _street_address;
		
		private string _city;
		
		private string _adopter_state;
		
		private string _zip;
		
		private string _urban_rural;
		
		private System.Nullable<int> _number_of_kids;
		
		private System.Nullable<bool> _other_pets;
		
		private string _pets_adopted;
		
		private System.Nullable<double> _balance_paid;
		
		private System.Nullable<int> _animal_id;
		
		private EntityRef<Animal> _Animal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmember_idChanging(string value);
    partial void Onmember_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onstreet_addressChanging(string value);
    partial void Onstreet_addressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void Onadopter_stateChanging(string value);
    partial void Onadopter_stateChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void Onurban_ruralChanging(string value);
    partial void Onurban_ruralChanged();
    partial void Onnumber_of_kidsChanging(System.Nullable<int> value);
    partial void Onnumber_of_kidsChanged();
    partial void Onother_petsChanging(System.Nullable<bool> value);
    partial void Onother_petsChanged();
    partial void Onpets_adoptedChanging(string value);
    partial void Onpets_adoptedChanged();
    partial void Onbalance_paidChanging(System.Nullable<double> value);
    partial void Onbalance_paidChanged();
    partial void Onanimal_idChanging(System.Nullable<int> value);
    partial void Onanimal_idChanged();
    #endregion
		
		public Adopter()
		{
			this._Animal = default(EntityRef<Animal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_member_id", DbType="VarChar(50)")]
		public string member_id
		{
			get
			{
				return this._member_id;
			}
			set
			{
				if ((this._member_id != value))
				{
					this.Onmember_idChanging(value);
					this.SendPropertyChanging();
					this._member_id = value;
					this.SendPropertyChanged("member_id");
					this.Onmember_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(50)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street_address", DbType="VarChar(50)")]
		public string street_address
		{
			get
			{
				return this._street_address;
			}
			set
			{
				if ((this._street_address != value))
				{
					this.Onstreet_addressChanging(value);
					this.SendPropertyChanging();
					this._street_address = value;
					this.SendPropertyChanged("street_address");
					this.Onstreet_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adopter_state", DbType="VarChar(25)")]
		public string adopter_state
		{
			get
			{
				return this._adopter_state;
			}
			set
			{
				if ((this._adopter_state != value))
				{
					this.Onadopter_stateChanging(value);
					this.SendPropertyChanging();
					this._adopter_state = value;
					this.SendPropertyChanged("adopter_state");
					this.Onadopter_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(10)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urban_rural", DbType="VarChar(5)")]
		public string urban_rural
		{
			get
			{
				return this._urban_rural;
			}
			set
			{
				if ((this._urban_rural != value))
				{
					this.Onurban_ruralChanging(value);
					this.SendPropertyChanging();
					this._urban_rural = value;
					this.SendPropertyChanged("urban_rural");
					this.Onurban_ruralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number_of_kids", DbType="Int")]
		public System.Nullable<int> number_of_kids
		{
			get
			{
				return this._number_of_kids;
			}
			set
			{
				if ((this._number_of_kids != value))
				{
					this.Onnumber_of_kidsChanging(value);
					this.SendPropertyChanging();
					this._number_of_kids = value;
					this.SendPropertyChanged("number_of_kids");
					this.Onnumber_of_kidsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_pets", DbType="Bit")]
		public System.Nullable<bool> other_pets
		{
			get
			{
				return this._other_pets;
			}
			set
			{
				if ((this._other_pets != value))
				{
					this.Onother_petsChanging(value);
					this.SendPropertyChanging();
					this._other_pets = value;
					this.SendPropertyChanged("other_pets");
					this.Onother_petsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pets_adopted", DbType="VarChar(50)")]
		public string pets_adopted
		{
			get
			{
				return this._pets_adopted;
			}
			set
			{
				if ((this._pets_adopted != value))
				{
					this.Onpets_adoptedChanging(value);
					this.SendPropertyChanging();
					this._pets_adopted = value;
					this.SendPropertyChanged("pets_adopted");
					this.Onpets_adoptedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance_paid", DbType="Float")]
		public System.Nullable<double> balance_paid
		{
			get
			{
				return this._balance_paid;
			}
			set
			{
				if ((this._balance_paid != value))
				{
					this.Onbalance_paidChanging(value);
					this.SendPropertyChanging();
					this._balance_paid = value;
					this.SendPropertyChanged("balance_paid");
					this.Onbalance_paidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_animal_id", DbType="Int")]
		public System.Nullable<int> animal_id
		{
			get
			{
				return this._animal_id;
			}
			set
			{
				if ((this._animal_id != value))
				{
					if (this._Animal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onanimal_idChanging(value);
					this.SendPropertyChanging();
					this._animal_id = value;
					this.SendPropertyChanged("animal_id");
					this.Onanimal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Animal_Adopter", Storage="_Animal", ThisKey="animal_id", OtherKey="animal_id", IsForeignKey=true)]
		public Animal Animal
		{
			get
			{
				return this._Animal.Entity;
			}
			set
			{
				Animal previousValue = this._Animal.Entity;
				if (((previousValue != value) 
							|| (this._Animal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Animal.Entity = null;
						previousValue.Adopters.Remove(this);
					}
					this._Animal.Entity = value;
					if ((value != null))
					{
						value.Adopters.Add(this);
						this._animal_id = value.animal_id;
					}
					else
					{
						this._animal_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Animal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
